package cli

import (
	"fmt"
	"net"
	"net/url"
	"strings"
	"sync/atomic"
	"time"

	"github.com/spf13/cobra"

	"github.com/shuaiZend/mage-mediagc/internal/action"
	"github.com/shuaiZend/mage-mediagc/internal/config"
	"github.com/shuaiZend/mage-mediagc/internal/magento"
	"github.com/shuaiZend/mage-mediagc/internal/media"
	"github.com/shuaiZend/mage-mediagc/internal/warm"
)

func newCacheCmd(a *app) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "cache",
		Short: "Manage Magento's derived thumbnail cache",
		Long: `Magento stores every resized variant under catalog/product/cache/<md5(params)>/.

Those files are derived data: they are regenerated on first request and no
database row refers to them by name. Emptying the tree is the safest large
win available, typically 15-30% of media size.

Emptying it is not free, though: every variant the next visitor asks for has
to be generated then, on the request path. cache warm refills the tree up
front by requesting the derived URLs through the storefront, which is both
faster and kinder to whoever is browsing while it runs.

  cache stats   measure the tree
  cache clean   empty it
  cache warm    refill it by requesting the derived URLs`,
	}
	cmd.AddCommand(newCacheStatsCmd(a), newCacheCleanCmd(a), newCacheWarmCmd(a))
	return cmd
}

func newCacheStatsCmd(a *app) *cobra.Command {
	return &cobra.Command{
		Use:   "stats",
		Short: "Report the size and file count of the derived cache",
		RunE: func(cmd *cobra.Command, _ []string) error {
			if err := a.cfg.Validate(config.ModeLocal); err != nil {
				return err
			}
			if err := action.EnsureMediaPathExists(a.cfg.Magento.MediaPath); err != nil {
				return err
			}
			files, bytes, err := action.CacheStats(cmd.Context(), a.cfg.Magento.MediaPath)
			if err != nil {
				return err
			}
			fmt.Fprintf(a.stdout, "cache dir : %s\n", a.cfg.Magento.MediaPath+"/"+media.CacheDirName)
			fmt.Fprintf(a.stdout, "files     : %d\n", files)
			fmt.Fprintf(a.stdout, "size      : %s\n", media.HumanBytes(bytes))
			if files == 0 {
				fmt.Fprintf(a.stdout, "\nnothing to clean\n")
			}
			return nil
		},
	}
}

func newCacheCleanCmd(a *app) *cobra.Command {
	var (
		apply      bool
		saveHashes string
	)
	cmd := &cobra.Command{
		Use:   "clean",
		Short: "Empty the derived thumbnail cache (regenerated automatically)",
		Long: `Empties catalog/product/cache and recreates the directory with the same
ownership, so the web server can keep writing to it.

This operation is safe and reversible in the only sense that matters: the
content is regenerated by Magento on demand. Expect a temporary slowdown on
the first requests after cleaning.

Magento regenerates a variant when something asks for it, so the way to avoid
that slowdown is to ask for everything in advance:

  mage-mediagc cache clean --apply --save-hashes var/cache-hashes.txt
  mage-mediagc cache warm  --hash-file var/cache-hashes.txt --apply

--save-hashes records the size sets present in the tree before it is emptied.
The tree is the cheapest place to read them from, so keeping a copy means
cache warm does not have to spend a request recovering one. It is a shortcut
rather than a requirement: a warm run that starts from an empty tree asks the
shop once, and carries on from there.

Reach for this rather than bin/magento catalog:images:resize, which is
single-threaded, re-resizes variants that already exist and cannot be
interrupted. Both do the same work; the warm command does it concurrently
against the storefront and skips whatever is already generated.

Without --apply only the planned work is reported, and no hash file is
written.`,
		Example: `  mage-mediagc cache clean            # measure only
  mage-mediagc cache clean --apply    # do it
  mage-mediagc cache clean --apply --save-hashes var/cache-hashes.txt`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if err := a.cfg.Validate(config.ModeLocal); err != nil {
				return err
			}

			// Snapshot the size sets before they are destroyed. This runs
			// ahead of the deletion on purpose: if the write fails, the cache
			// is still intact, so the operator has lost nothing and can fix
			// the path and try again.
			if apply && saveHashes != "" {
				dir := warm.CacheDir(a.cfg.Magento.MediaPath)
				hashes, err := warm.DiscoverHashes(dir)
				if err != nil {
					return err
				}
				if len(hashes) == 0 {
					return fmt.Errorf("cannot save hashes: %s holds no size-set directories", dir)
				}
				if err := warm.WriteHashFile(saveHashes, hashes); err != nil {
					return err
				}
				fmt.Fprintf(a.stdout, "hashes recorded: %d size sets in %s\n", len(hashes), saveHashes)
			}

			res, err := action.CleanCache(cmd.Context(), a.cfg.Magento.MediaPath, !apply, nil)
			if err != nil {
				return err
			}

			verb := "would remove"
			if apply {
				verb = "removed"
			}
			fmt.Fprintf(a.stdout, "%s: %s\n", a.cfg.Magento.MediaPath+"/"+media.CacheDirName, verb)
			fmt.Fprintf(a.stdout, "  files : %d\n", res.RemovedFiles)
			fmt.Fprintf(a.stdout, "  size  : %s\n", media.HumanBytes(res.RemovedBytes))
			if apply {
				fmt.Fprintf(a.stdout, "  cache directory recreated: %v\n", res.Recreated)
				fmt.Fprintf(a.stdout, "\nMagento will regenerate cached images on demand.\n")
				if saveHashes != "" {
					fmt.Fprintf(a.stdout, "Refill it up front with:\n  mage-mediagc cache warm --hash-file %s --apply\n",
						saveHashes)
				} else {
					fmt.Fprintf(a.stdout, "Nothing recorded which size sets existed, so cache warm will ask the shop\n")
					fmt.Fprintf(a.stdout, "for one before it starts.\n")
				}
			} else if res.RemovedFiles > 0 {
				fmt.Fprintf(a.stdout, "\nrun again with --apply to perform the cleanup\n")
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&apply, "apply", false, "perform the deletion (default is a dry run)")
	cmd.Flags().StringVar(&saveHashes, "save-hashes", "",
		"record the size sets to this file before deleting, for `cache warm --hash-file`")
	return cmd
}

func newCacheWarmCmd(a *app) *cobra.Command {
	var (
		apply            bool
		baseURL          string
		cacheHash        string
		hashFile         string
		concurrency      int
		timeout          time.Duration
		method           string
		userAgent        string
		rate             int
		maxRequests      int
		maxErrorFraction float64
		liveOnly         bool
		noProbe          bool
		loopback         bool
		resolve          []string
		insecure         bool
		skipSupportCheck bool
	)
	cmd := &cobra.Command{
		Use:   "warm",
		Short: "Refill the derived thumbnail cache by requesting the derived URLs",
		Long: `warm refills catalog/product/cache by requesting the URLs the cache would
serve from, which makes Magento generate each missing variant on demand —
through exactly the code path a visitor's browser takes.

Nothing has to be installed on the shop. No PHP runtime, no bin/magento, no
Composer, no module. The tool needs HTTP access to the storefront and nothing
else, so it can run from a laptop, a bastion host or a CI job against a shop
it has no shell on.

One request per original
  Since Magento 2.3, a single request for one cached URL regenerates that
  image's variant in every size set the theme defines. The run therefore
  issues one request per original image, not one per variant — twenty-five
  times less traffic than the URL space suggests. Variants that already
  exist are skipped with a local stat rather than a request, so an interrupted
  run resumes for almost nothing: run it again and it finds only what is
  still missing.

Magento 2.2 and earlier are refused
  Those releases generate nothing on request, so every URL warm would ask for
  fails. The check looks for the resize service under vendor/ rather than at a
  version string, and stops before the media tree is walked. Override with
  --skip-support-check once you have confirmed otherwise by hand.

Reaching the storefront without leaving the machine
  On the shop's own server, sending the traffic out to the public address and
  back costs bandwidth and depends on DNS. --loopback dials 127.0.0.1 while
  keeping the request's Host header and TLS server name, so the web server
  still routes it to the right site:

    mage-mediagc cache warm --loopback --apply

  That is also what makes the command usable on a host serving several shops.
  The usual workaround — pointing the domain at 127.0.0.1 in /etc/hosts —
  sends every request to whichever vhost the server treats as the default,
  and does so silently, because the default vhost answers perfectly well.
  --resolve host:port:address overrides one host and port when loopback is not
  enough. If that shop's certificate is self-signed for an internal name, and
  therefore carries no subject alternative name, Go refuses it outright —
  --insecure-skip-verify accepts it, and the run says so in its output.

Which size set the requests are routed through
  A request names a size set in its path, and the set has to be one the theme
  asks for, or the path that was asked for is never created. Which one does
  not matter — a request regenerates every set either way, and the hash itself
  cannot be computed outside PHP. So it is taken from --cache-hash, from
  warm.cacheHash, from --hash-file, or read off the cache tree; and when the
  tree is empty and nothing was supplied, one request is issued to make the
  shop reveal the sets it uses.

  The value is then confirmed against the tree, so a stale one left behind by
  an earlier theme or store configuration is corrected instead of quietly
  wasting the run. Sizes are derived from both, so editing either orphans
  every existing size-set directory forever.

Emptying the cache destroys the shortcut
  The tree is the cheapest place to read the size sets from, so a snapshot
  saves the one request a cold start costs:

    mage-mediagc cache clean --apply --save-hashes var/cache-hashes.txt
    mage-mediagc cache warm  --hash-file var/cache-hashes.txt --apply

  Without one, warm recovers a set on its own.

Safety rails
  - one request is issued first, on its own, and the expected cache file is
    looked for. If no file appears the run stops there, because the
    alternative is hundreds of thousands of requests that return 200 and
    generate nothing — the signature of a CDN or reverse proxy answering from
    the edge without the origin ever being involved. Pass --no-probe to skip
    the check once you have confirmed the URL mapping by hand
  - the run fails when more than --max-error-fraction of the requests did not
    return 2xx, which usually means the wrong host or a WAF rejecting the
    client
  - image files whose path is not two directories and a file name are excluded
    and counted. Magento recovers the original from the last three path
    segments, so at any other depth the request would resolve to a different
    image and quietly generate that one instead
  - without --apply nothing is requested

--live-only needs database access: it runs the usual reference analysis and
skips orphaned originals, which is the right choice for a shop that has not
been cleaned yet. It costs a full scan and reference collection, so it is off
by default.`,
		Example: `  # See the size of the job first, then do it
  mage-mediagc cache warm
  mage-mediagc cache warm --apply

  # On the web server itself, without leaving the machine
  mage-mediagc cache warm --loopback --apply

  # Refill after an intended clean
  mage-mediagc cache warm --hash-file var/cache-hashes.txt --apply

  # Run from a host with no database access at all
  mage-mediagc cache warm --base-url https://shop.example.com --apply

  # Only warm images that are still referenced
  mage-mediagc cache warm --live-only --apply

  # Measure throughput before committing to the whole catalog
  mage-mediagc cache warm --max-requests 500 --apply`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			ctx := cmd.Context()
			if err := a.cfg.Validate(config.ModeLocal); err != nil {
				return err
			}
			if err := action.EnsureMediaPathExists(a.cfg.Magento.MediaPath); err != nil {
				return err
			}
			mediaRoot := a.cfg.Magento.MediaPath

			// Nothing below can work on a release that does not generate
			// derived images on request, and the symptom it produces — 404s,
			// or 200s that write nothing — points at the wrong cause. Checking
			// first costs one stat and a directory read.
			if !skipSupportCheck {
				if err := warm.CheckOnDemandSupport(a.cfg.Magento.Root); err != nil {
					return err
				}
			}

			// The connection is opened lazily and the settings are demanded
			// only here. With an explicit --base-url and no --live-only,
			// warming a shop whose database this host cannot reach is a
			// perfectly reasonable thing to do.
			var client *magento.Client
			defer func() {
				if client != nil {
					_ = client.Close()
				}
			}()

			rawBase := resolveFlag(cmd, "base-url", baseURL, a.cfg.Warm.BaseURL)
			if rawBase == "" || liveOnly {
				if err := a.cfg.RequireDatabase(); err != nil {
					return err
				}
				c, err := a.openDB(ctx)
				if err != nil {
					return err
				}
				client = c
			}
			if rawBase == "" {
				found, err := client.BaseURL(ctx)
				if err != nil {
					return err
				}
				rawBase = found
			}
			base, err := warm.ParseBaseURL(rawBase)
			if err != nil {
				return err
			}

			// Address overrides are settled here, with the rest of the
			// configuration, so a mistake costs nothing: everything after this
			// point may walk a catalog with a million files in it. The loopback
			// mapping goes down first and the explicit entries over it, so a
			// --resolve always wins over the convenience.
			resolved, err := warm.ParseResolveEntries(
				append(append([]string(nil), a.cfg.Warm.Resolve...), resolve...))
			if err != nil {
				return err
			}
			if loopback || (len(resolve) == 0 && a.cfg.Warm.Loopback) {
				merged := warm.LoopbackResolve(base)
				if merged == nil {
					return fmt.Errorf("--loopback needs a base URL with a host, got %q", base.String())
				}
				for k, v := range resolved {
					merged[k] = v
				}
				resolved = merged
			}

			opts := warm.Options{
				Concurrency:        resolveFlag(cmd, "concurrency", concurrency, a.cfg.Warm.Concurrency),
				Timeout:            resolveFlag(cmd, "timeout", timeout, a.cfg.Warm.Timeout.Std()),
				Method:             resolveFlag(cmd, "method", method, a.cfg.Warm.Method),
				UserAgent:          resolveFlag(cmd, "user-agent", userAgent, a.cfg.Warm.UserAgent),
				Rate:               resolveFlag(cmd, "rate", rate, a.cfg.Warm.Rate),
				MaxRequests:        resolveFlag(cmd, "max-requests", maxRequests, a.cfg.Warm.MaxRequests),
				MaxErrorFraction:   resolveFlag(cmd, "max-error-fraction", maxErrorFraction, a.cfg.Warm.MaxErrorFraction),
				Resolve:            resolved,
				InsecureSkipVerify: insecure || a.cfg.Warm.InsecureSkipVerify,
				NoProbe:            noProbe,
				DryRun:             !apply,
			}
			if opts.UserAgent == "" {
				opts.UserAgent = defaultUserAgent()
			}

			// Reject the settings that would otherwise be silently corrected
			// further down: a concurrency of 0 becomes one worker, a timeout
			// of 0 becomes thirty seconds, and a zero error fraction becomes
			// the default. Quietly overriding what the operator typed is worse
			// than refusing it, and a dry run exists precisely to refuse it.
			// The method is checked here for the same reason: the run would
			// reject it anyway, but only after the media tree had been walked.
			switch {
			case opts.Concurrency < 1:
				return fmt.Errorf("--concurrency must be at least 1, got %d", opts.Concurrency)
			case opts.Timeout <= 0:
				return fmt.Errorf("--timeout must be positive, got %s", opts.Timeout)
			case opts.Rate < 0:
				return fmt.Errorf("--rate cannot be negative, got %d", opts.Rate)
			case opts.MaxRequests < 0:
				return fmt.Errorf("--max-requests cannot be negative, got %d", opts.MaxRequests)
			case opts.MaxErrorFraction <= 0 || opts.MaxErrorFraction > 1:
				return fmt.Errorf("--max-error-fraction must be in (0, 1], got %g", opts.MaxErrorFraction)
			}
			if _, err := warm.ParseMethod(opts.Method); err != nil {
				return err
			}

			// Work out which size set to route the requests through. The most
			// explicit source wins: a hash given by hand is a deliberate
			// statement, a snapshot is a recollection, and discovery is a guess
			// at what the tree happens to hold.
			fileForHashes := resolveFlag(cmd, "hash-file", hashFile, a.cfg.Warm.HashFile)
			chosen := strings.TrimSpace(resolveFlag(cmd, "cache-hash", cacheHash, a.cfg.Warm.CacheHash))
			source := ""
			switch {
			case chosen != "":
				source = "given with --cache-hash"
			case fileForHashes != "":
				loaded, err := warm.ReadHashFile(fileForHashes)
				if err != nil {
					return fmt.Errorf("read hash file: %w", err)
				}
				if len(loaded) == 0 {
					return fmt.Errorf("%s lists no cache hashes", fileForHashes)
				}
				chosen, source = loaded[0], "read from "+fileForHashes
			default:
				dir := warm.CacheDir(mediaRoot)
				found, err := warm.DiscoverHashes(dir)
				if err != nil {
					return err
				}
				if len(found) > 0 {
					chosen, source = found[0], "discovered in "+dir
				}
			}
			if chosen != "" && !warm.ValidHash(chosen) {
				return fmt.Errorf("invalid cache hash %q: expected 32 lowercase hex characters", chosen)
			}
			trusted := chosen != ""
			if chosen == "" {
				// Nothing on the host knows and nothing the operator said
				// applies, so the run starts from the placeholder set and lets
				// the shop name the real one. See warm.SeedHash.
				chosen, source = warm.SeedHash, "not known yet; the first request resolves it"
			}

			// Collect the originals to pair with the size set.
			quiet := a.cfg.Output.Quiet
			var files []media.File
			if liveOnly {
				analysis, err := a.analyzeWith(ctx, client, analyzeOptions{showProgress: !quiet})
				if err != nil {
					return err
				}
				orphans := analysis.OrphanSet()
				scanned := analysis.Scan()
				files = make([]media.File, 0, len(scanned.Files))
				for _, f := range scanned.Files {
					if _, dead := orphans[f.RelPath]; dead {
						continue
					}
					files = append(files, f)
				}
				if !quiet {
					fmt.Fprintf(a.stderr, "  %d of %d files are still referenced\n",
						len(files), len(scanned.Files))
				}
			} else {
				var scanProgress func(int64)
				if !quiet {
					printer := a.progressPrinter("  indexed")
					scanProgress = func(n int64) { printer(n, 0) }
				}
				scan, err := media.Scan(ctx, mediaRoot, media.ScanOptions{
					Workers: a.cfg.Scan.Workers,
					// The cache tree is this command's output. Indexing it
					// would pair generated files with size sets and multiply
					// the work for nothing.
					IncludeCache: false,
					ExcludeGlobs: a.cfg.Scan.ExcludeGlobs,
					Progress:     scanProgress,
				})
				if err != nil {
					return err
				}
				if !quiet {
					fmt.Fprintf(a.stderr, "\r  indexed %d files (%s)\n",
						len(scan.Files), media.HumanBytes(scan.Bytes))
				}
				files = scan.Files
			}

			// Confirm the size set against what the tree holds, and repair it
			// when it does not match. A set the theme has stopped asking for
			// leaves every requested path absent: the run would look like a
			// total failure, and the next attempt would re-request everything
			// because nothing it asked for exists. Confirming costs one
			// request, and only when nothing on disk can answer.
			firstRel := firstWarmable(files)
			verified := false
			if firstRel != "" {
				if live, liveErr := warm.LiveHash(warm.CacheDir(mediaRoot), firstRel); liveErr == nil {
					if live != chosen {
						fmt.Fprintf(a.stderr,
							"  %s is not a size set this shop uses; routing through %s instead\n",
							chosen, live)
					}
					chosen, source, verified = live, "confirmed against the cache tree", true
				}
			}
			if firstRel != "" && !verified {
				switch {
				case !apply:
					// A dry run issues nothing, by contract. The size of the
					// job does not depend on which set is used, so the report
					// stays honest as long as it says the set is unconfirmed.
					source += " (unconfirmed: a real run resolves it)"
				case opts.NoProbe && !trusted:
					return fmt.Errorf("no size set could be read from %s and none was supplied, "+
						"and --no-probe forbids the one request that would find one. "+
						"Drop --no-probe, or name a set with --cache-hash",
						warm.CacheDir(mediaRoot))
				case opts.NoProbe:
					source += " (unconfirmed: --no-probe)"
				default:
					if !quiet {
						fmt.Fprintf(a.stderr,
							"  no variant found under the cache tree; asking the shop which size sets it uses\n")
					}
					live, seedErr := warm.Seed(ctx, mediaRoot, firstRel, base, opts)
					if seedErr != nil {
						return seedErr
					}
					chosen, source = live, "recovered from the shop"
				}
			}

			plan, err := warm.BuildPlan(mediaRoot, files, chosen, base)
			if err != nil {
				return err
			}

			// Progress lines are written from the worker goroutines, so the
			// "did we print anything" flag has to be atomic.
			var progressLines atomic.Int64
			if !quiet {
				opts.Progress = func(done, total int64, _ string) {
					progressLines.Add(1)
					fmt.Fprintf(a.stderr, "\r  requested %d/%d", done, total)
				}
			}

			res, runErr := warm.Run(ctx, plan, opts)
			if progressLines.Load() > 0 {
				fmt.Fprintln(a.stderr)
			}

			// This block describes the plan, not the outcome: "to request" is
			// how much work there is, which is what a dry run is asked for and
			// what an applying run is measured against. What actually happened
			// is reported separately below, so the two cannot be confused.
			fmt.Fprintf(a.stdout, "%-14s: %s\n", "media root", mediaRoot)
			fmt.Fprintf(a.stdout, "%-14s: %s\n", "base url", base.String())
			fmt.Fprintf(a.stdout, "%-14s: %s\n", "route",
				describeRoute(base, opts.Resolve, opts.InsecureSkipVerify))
			fmt.Fprintf(a.stdout, "%-14s: %s\n", "size set", chosen)
			fmt.Fprintf(a.stdout, "%-14s: %s\n", "", source)
			// "N of M files" rather than two separate rows: only the images can
			// be paired with a size set, so this is the number the plan covers.
			fmt.Fprintf(a.stdout, "%-14s: %d of %d files\n", "images",
				warm.WarmableFiles(files), len(files))
			fmt.Fprintf(a.stdout, "%-14s: %d\n", "cached", res.Skipped)
			fmt.Fprintf(a.stdout, "%-14s: %d\n", "to request", res.Pending)
			if plan.Ineligible > 0 {
				fmt.Fprintf(a.stdout, "%-14s: %d\n", "excluded", plan.Ineligible)
			}

			if res.Pending == 0 {
				fmt.Fprintf(a.stdout, "\nnothing to do: every image already has a cached variant\n")
				return nil
			}
			if !apply {
				fmt.Fprintf(a.stdout, "\nrun again with --apply to issue the requests\n")
				return nil
			}

			// OK counts every 2xx, and the pre-flight request is one of them:
			// the variant it asks for really is generated, so it belongs in
			// the total rather than being quietly excluded.
			fmt.Fprintf(a.stdout, "\nwarmed %d of %d images in %s\n",
				res.OK, res.Pending, res.Duration.Round(time.Millisecond))
			fmt.Fprintf(a.stdout, "  requests  : %d\n", res.Requests)
			if res.ClientErrors > 0 {
				fmt.Fprintf(a.stdout, "  rejected  : %d (4xx)\n", res.ClientErrors)
			}
			if res.ServerErrors > 0 {
				fmt.Fprintf(a.stdout, "  server    : %d (5xx)\n", res.ServerErrors)
			}
			if res.TransportErrors > 0 {
				fmt.Fprintf(a.stdout, "  transport : %d (never completed)\n", res.TransportErrors)
			}
			if res.Other > 0 {
				fmt.Fprintf(a.stdout, "  other     : %d\n", res.Other)
			}
			if res.Truncated {
				fmt.Fprintf(a.stdout, "  truncated : --max-requests reached\n")
			}

			if res.Truncated {
				fmt.Fprintf(a.stdout, "\nrun again to continue: images cached by then are skipped without a request\n")
			}
			if runErr != nil {
				return runErr
			}
			if failed := res.Failures(); failed > 0 {
				fmt.Fprintf(a.stdout, "\n%d requests did not return 2xx; a visitor will trigger those images on demand\n",
					failed)
			}
			return nil
		},
	}

	fl := cmd.Flags()
	fl.BoolVar(&apply, "apply", false, "issue the requests (default is a dry run)")
	fl.StringVar(&baseURL, "base-url", "",
		"storefront base URL (default: web/secure/base_url from core_config_data, which needs the database)")
	fl.StringVar(&cacheHash, "cache-hash", "",
		"size set to route the requests through (default: read from the cache tree, or recovered with one request)")
	fl.StringVar(&hashFile, "hash-file", "",
		"read size sets from this file (default warm.hashFile)")
	fl.BoolVar(&loopback, "loopback", false,
		"dial 127.0.0.1 instead of the address the domain resolves to, keeping the Host header and TLS name")
	fl.StringSliceVar(&resolve, "resolve", nil,
		"replace the address dialed for one host, as host:port:address; repeatable")
	fl.BoolVar(&insecure, "insecure-skip-verify", false,
		"accept any TLS certificate; needed for a shop whose https certificate is self-signed with no SAN")
	fl.BoolVar(&skipSupportCheck, "skip-support-check", false,
		"warm even when the install looks like Magento 2.2, which cannot generate variants on request")
	fl.IntVar(&concurrency, "concurrency", 0,
		"parallel requests (default warm.concurrency, 4)")
	fl.DurationVar(&timeout, "timeout", 0,
		"timeout for one request (default warm.timeout, 30s)")
	fl.StringVar(&method, "method", "",
		"get or head (default warm.method, get)")
	fl.StringVar(&userAgent, "user-agent", "",
		"User-Agent header to send (default: names and versions the tool)")
	fl.IntVar(&rate, "rate", 0,
		"cap on request starts per second across all workers, 0 = no limit")
	fl.IntVar(&maxRequests, "max-requests", 0,
		"stop after this many requests, 0 = no limit")
	fl.Float64Var(&maxErrorFraction, "max-error-fraction", 0,
		"abort when the share of failed requests exceeds this, 0-1 (default warm.maxErrorFraction, 0.05)")
	fl.BoolVar(&liveOnly, "live-only", false,
		"warm only images that are still referenced (needs the database, runs the full analysis)")
	fl.BoolVar(&noProbe, "no-probe", false,
		"skip the pre-flight check that a request produces a cache file")
	return cmd
}

// firstWarmable returns the relative path of the first image the plan would
// cover, or "" when there is none.
//
// It is the subject of the one request that establishes which size sets the
// theme asks for, so it has to be a file that can actually be warmed: a
// non-image, or a path at the wrong depth, would be resolved by Magento
// against some other original and answer nothing useful.
func firstWarmable(files []media.File) string {
	for i := range files {
		if warm.WarmableFiles(files[i:i+1]) == 1 {
			return files[i].RelPath
		}
	}
	return ""
}

// describeRoute renders how the requests will reach the storefront, which is
// the first thing to check when a run behaves as if it were talking to the
// wrong site.
func describeRoute(base *url.URL, resolve map[string]string, insecure bool) string {
	route := "direct (" + base.Hostname() + ")"
	if len(resolve) == 0 {
		return withTLS(route, base, insecure)
	}
	port := base.Port()
	if port == "" {
		if base.Scheme == "https" {
			port = "443"
		} else {
			port = "80"
		}
	}
	if addr, ok := resolve[net.JoinHostPort(base.Hostname(), port)]; ok {
		return withTLS(fmt.Sprintf("%s, Host: %s", addr, base.Hostname()), base, insecure)
	}
	return withTLS(fmt.Sprintf("overridden for %d address(es)", len(resolve)), base, insecure)
}

// withTLS appends a warning when certificate verification is off. The run's
// output is the only place an operator can see that it is, and a warm run is
// long enough that nobody re-reads the command line it was started with.
func withTLS(route string, base *url.URL, insecure bool) string {
	if !insecure || base.Scheme != "https" {
		return route
	}
	return route + ", TLS not verified"
}
