package cli

import (
	"fmt"
	"sync/atomic"
	"time"

	"github.com/spf13/cobra"

	"github.com/shuaiZend/mage-mediagc/internal/action"
	"github.com/shuaiZend/mage-mediagc/internal/config"
	"github.com/shuaiZend/mage-mediagc/internal/magento"
	"github.com/shuaiZend/mage-mediagc/internal/media"
	"github.com/shuaiZend/mage-mediagc/internal/warm"
)

func newCacheCmd(a *app) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "cache",
		Short: "Manage Magento's derived thumbnail cache",
		Long: `Magento stores every resized variant under catalog/product/cache/<md5(params)>/.

Those files are derived data: they are regenerated on first request and no
database row refers to them by name. Emptying the tree is the safest large
win available, typically 15-30% of media size.

Emptying it is not free, though: every variant the next visitor asks for has
to be generated then, on the request path. cache warm refills the tree up
front by requesting the derived URLs through the storefront, which is both
faster and kinder to whoever is browsing while it runs.

  cache stats   measure the tree
  cache clean   empty it
  cache warm    refill it by requesting the derived URLs`,
	}
	cmd.AddCommand(newCacheStatsCmd(a), newCacheCleanCmd(a), newCacheWarmCmd(a))
	return cmd
}

func newCacheStatsCmd(a *app) *cobra.Command {
	return &cobra.Command{
		Use:   "stats",
		Short: "Report the size and file count of the derived cache",
		RunE: func(cmd *cobra.Command, _ []string) error {
			if err := a.cfg.Validate(config.ModeLocal); err != nil {
				return err
			}
			if err := action.EnsureMediaPathExists(a.cfg.Magento.MediaPath); err != nil {
				return err
			}
			files, bytes, err := action.CacheStats(cmd.Context(), a.cfg.Magento.MediaPath)
			if err != nil {
				return err
			}
			fmt.Fprintf(a.stdout, "cache dir : %s\n", a.cfg.Magento.MediaPath+"/"+media.CacheDirName)
			fmt.Fprintf(a.stdout, "files     : %d\n", files)
			fmt.Fprintf(a.stdout, "size      : %s\n", media.HumanBytes(bytes))
			if files == 0 {
				fmt.Fprintf(a.stdout, "\nnothing to clean\n")
			}
			return nil
		},
	}
}

func newCacheCleanCmd(a *app) *cobra.Command {
	var (
		apply      bool
		saveHashes string
	)
	cmd := &cobra.Command{
		Use:   "clean",
		Short: "Empty the derived thumbnail cache (regenerated automatically)",
		Long: `Empties catalog/product/cache and recreates the directory with the same
ownership, so the web server can keep writing to it.

This operation is safe and reversible in the only sense that matters: the
content is regenerated by Magento on demand. Expect a temporary slowdown on
the first requests after cleaning.

Magento regenerates a variant when something asks for it, so the way to avoid
that slowdown is to ask for everything in advance:

  mage-mediagc cache clean --apply --save-hashes var/cache-hashes.txt
  mage-mediagc cache warm  --hash-file var/cache-hashes.txt --apply

--save-hashes records the size-set hashes present in the tree before it is
emptied. Nothing on the host remembers them afterwards: they are derived from
the theme's view.xml rather than stored, and once the tree is gone there is
nothing left to discover them from. Without the snapshot, cache warm has to
wait for the first visitors to reveal each size set, one variant at a time.

Reach for this rather than bin/magento catalog:images:resize, which is
single-threaded, re-resizes variants that already exist and cannot be
interrupted. Both do the same work; the warm command does it concurrently
against the storefront and skips whatever is already generated.

Without --apply only the planned work is reported, and no hash file is
written.`,
		Example: `  mage-mediagc cache clean            # measure only
  mage-mediagc cache clean --apply    # do it
  mage-mediagc cache clean --apply --save-hashes var/cache-hashes.txt`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if err := a.cfg.Validate(config.ModeLocal); err != nil {
				return err
			}

			// Snapshot the size sets before they are destroyed. This runs
			// ahead of the deletion on purpose: if the write fails, the cache
			// is still intact, so the operator has lost nothing and can fix
			// the path and try again.
			if apply && saveHashes != "" {
				dir := warm.CacheDir(a.cfg.Magento.MediaPath)
				hashes, err := warm.DiscoverHashes(dir)
				if err != nil {
					return err
				}
				if len(hashes) == 0 {
					return fmt.Errorf("cannot save hashes: %s holds no size-set directories", dir)
				}
				if err := warm.WriteHashFile(saveHashes, hashes); err != nil {
					return err
				}
				fmt.Fprintf(a.stdout, "hashes recorded: %d size sets in %s\n", len(hashes), saveHashes)
			}

			res, err := action.CleanCache(cmd.Context(), a.cfg.Magento.MediaPath, !apply, nil)
			if err != nil {
				return err
			}

			verb := "would remove"
			if apply {
				verb = "removed"
			}
			fmt.Fprintf(a.stdout, "%s: %s\n", a.cfg.Magento.MediaPath+"/"+media.CacheDirName, verb)
			fmt.Fprintf(a.stdout, "  files : %d\n", res.RemovedFiles)
			fmt.Fprintf(a.stdout, "  size  : %s\n", media.HumanBytes(res.RemovedBytes))
			if apply {
				fmt.Fprintf(a.stdout, "  cache directory recreated: %v\n", res.Recreated)
				fmt.Fprintf(a.stdout, "\nMagento will regenerate cached images on demand.\n")
				if saveHashes != "" {
					fmt.Fprintf(a.stdout, "Refill it up front with:\n  mage-mediagc cache warm --hash-file %s --apply\n",
						saveHashes)
				} else {
					fmt.Fprintf(a.stdout, "Nothing recorded which size sets existed, so cache warm can only pick them\n")
					fmt.Fprintf(a.stdout, "up from the first visitors' requests.\n")
				}
			} else if res.RemovedFiles > 0 {
				fmt.Fprintf(a.stdout, "\nrun again with --apply to perform the cleanup\n")
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&apply, "apply", false, "perform the deletion (default is a dry run)")
	cmd.Flags().StringVar(&saveHashes, "save-hashes", "",
		"record the size-set hashes to this file before deleting, for `cache warm --hash-file`")
	return cmd
}

func newCacheWarmCmd(a *app) *cobra.Command {
	var (
		apply            bool
		baseURL          string
		hashes           []string
		hashFile         string
		concurrency      int
		timeout          time.Duration
		method           string
		userAgent        string
		rate             int
		maxRequests      int
		maxErrorFraction float64
		liveOnly         bool
		noProbe          bool
	)
	cmd := &cobra.Command{
		Use:   "warm",
		Short: "Refill the derived thumbnail cache by requesting the derived URLs",
		Long: `warm refills catalog/product/cache by requesting the URLs the cache would
serve from, which makes Magento generate each missing variant on demand —
through exactly the code path a visitor's browser takes.

Nothing has to be installed on the shop. No PHP runtime, no bin/magento, no
Composer, no module. The tool needs HTTP access to the storefront and nothing
else, so it can run from a laptop, a bastion host or a CI job against a shop
it has no shell on.

What gets requested
  Every original image is paired with every size set the theme asks for. A
  size set is identified by the md5 hash Magento uses as its cache directory
  name, and those are discovered from media/catalog/product/cache/, or read
  back from a snapshot (see below), or supplied with --cache-hash. The hash is
  never computed: it is derived from PHP-side parameters, and guessing wrong
  would mean requesting a URL space that does not exist, where every request
  returns 200 and generates nothing at all.

  Variants that already exist are skipped with a local stat rather than a
  request, so an interrupted run resumes for almost nothing: run it again and
  it finds only what is still missing.

Emptying the cache destroys this knowledge
  The hashes can only be discovered while the cache still holds them:

    mage-mediagc cache clean --apply --save-hashes var/cache-hashes.txt
    mage-mediagc cache warm  --hash-file var/cache-hashes.txt --apply

  Without a snapshot, warm picks up whatever the first visitor happens to
  request and the rest is generated lazily, which is the behavior you were
  trying to avoid.

Safety rails
  - one request is issued first, on its own, and the expected cache file is
    looked for. If no file appears the run stops there, because the
    alternative is hundreds of thousands of requests that return 200 and
    generate nothing — the signature of a CDN or reverse proxy answering from
    the edge without the origin ever being involved. Pass --no-probe to skip
    the check once you have confirmed the URL mapping by hand
  - the run fails when more than --max-error-fraction of the requests did not
    return 2xx, which usually means the wrong host or a WAF rejecting the
    client
  - without --apply nothing is requested

--live-only needs database access: it runs the usual reference analysis and
skips orphaned originals, which is the right choice for a shop that has not
been cleaned yet. It costs a full scan and reference collection, so it is off
by default.`,
		Example: `  # See the size of the job first, then do it
  mage-mediagc cache warm
  mage-mediagc cache warm --apply

  # Refill after an intended clean
  mage-mediagc cache warm --hash-file var/cache-hashes.txt --apply

  # Run from a host with no database access at all
  mage-mediagc cache warm --base-url https://shop.example.com --apply

  # Only warm images that are still referenced
  mage-mediagc cache warm --live-only --apply

  # Measure throughput before committing to the whole catalog
  mage-mediagc cache warm --max-requests 500 --apply`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			ctx := cmd.Context()
			if err := a.cfg.Validate(config.ModeLocal); err != nil {
				return err
			}
			if err := action.EnsureMediaPathExists(a.cfg.Magento.MediaPath); err != nil {
				return err
			}
			mediaRoot := a.cfg.Magento.MediaPath

			// Resolve the size sets, most explicit source first. The order
			// matters: a hash given by hand is a deliberate statement about
			// what to warm, while discovery is a best guess at what the theme
			// happens to ask for.
			fileForHashes := resolveFlag(cmd, "hash-file", hashFile, a.cfg.Warm.HashFile)
			var (
				sizeSets []string
				source   string
			)
			switch {
			case len(hashes) > 0:
				sizeSets, source = hashes, "given with --cache-hash"
			case len(a.cfg.Warm.CacheHashes) > 0:
				sizeSets, source = a.cfg.Warm.CacheHashes, "given in warm.cacheHashes"
			case fileForHashes != "":
				loaded, err := warm.ReadHashFile(fileForHashes)
				if err != nil {
					return fmt.Errorf("read hash file: %w", err)
				}
				if len(loaded) == 0 {
					return fmt.Errorf("%s lists no cache hashes", fileForHashes)
				}
				sizeSets, source = loaded, "read from "+fileForHashes
			default:
				dir := warm.CacheDir(mediaRoot)
				found, err := warm.DiscoverHashes(dir)
				if err != nil {
					return err
				}
				sizeSets, source = found, "discovered in "+dir
			}
			if len(sizeSets) == 0 {
				return warm.ErrNoHashes
			}

			// The connection is opened lazily and the settings are demanded
			// only here. With an explicit --base-url and no --live-only,
			// warming a shop whose database this host cannot reach is a
			// perfectly reasonable thing to do.
			var client *magento.Client
			defer func() {
				if client != nil {
					_ = client.Close()
				}
			}()

			rawBase := resolveFlag(cmd, "base-url", baseURL, a.cfg.Warm.BaseURL)
			if rawBase == "" || liveOnly {
				if err := a.cfg.RequireDatabase(); err != nil {
					return err
				}
				c, err := a.openDB(ctx)
				if err != nil {
					return err
				}
				client = c
			}
			if rawBase == "" {
				found, err := client.BaseURL(ctx)
				if err != nil {
					return err
				}
				rawBase = found
			}
			base, err := warm.ParseBaseURL(rawBase)
			if err != nil {
				return err
			}

			opts := warm.Options{
				Concurrency:      resolveFlag(cmd, "concurrency", concurrency, a.cfg.Warm.Concurrency),
				Timeout:          resolveFlag(cmd, "timeout", timeout, a.cfg.Warm.Timeout.Std()),
				Method:           resolveFlag(cmd, "method", method, a.cfg.Warm.Method),
				UserAgent:        resolveFlag(cmd, "user-agent", userAgent, a.cfg.Warm.UserAgent),
				Rate:             resolveFlag(cmd, "rate", rate, a.cfg.Warm.Rate),
				MaxRequests:      resolveFlag(cmd, "max-requests", maxRequests, a.cfg.Warm.MaxRequests),
				MaxErrorFraction: resolveFlag(cmd, "max-error-fraction", maxErrorFraction, a.cfg.Warm.MaxErrorFraction),
				NoProbe:          noProbe,
				DryRun:           !apply,
			}
			if opts.UserAgent == "" {
				opts.UserAgent = defaultUserAgent()
			}

			// Reject the settings that would otherwise be silently corrected
			// further down: a concurrency of 0 becomes one worker, a timeout
			// of 0 becomes thirty seconds, and a zero error fraction becomes
			// the default. Quietly overriding what the operator typed is worse
			// than refusing it, and a dry run exists precisely to refuse it.
			// The method is checked here for the same reason: the run would
			// reject it anyway, but only after the media tree had been walked.
			switch {
			case opts.Concurrency < 1:
				return fmt.Errorf("--concurrency must be at least 1, got %d", opts.Concurrency)
			case opts.Timeout <= 0:
				return fmt.Errorf("--timeout must be positive, got %s", opts.Timeout)
			case opts.Rate < 0:
				return fmt.Errorf("--rate cannot be negative, got %d", opts.Rate)
			case opts.MaxRequests < 0:
				return fmt.Errorf("--max-requests cannot be negative, got %d", opts.MaxRequests)
			case opts.MaxErrorFraction <= 0 || opts.MaxErrorFraction > 1:
				return fmt.Errorf("--max-error-fraction must be in (0, 1], got %g", opts.MaxErrorFraction)
			}
			if _, err := warm.ParseMethod(opts.Method); err != nil {
				return err
			}

			// Everything above this point is configuration, so it is settled
			// before the media tree is walked: a typo in a flag should not
			// cost a scan of a catalog with a million files in it.

			// Collect the originals to pair with the size sets.
			quiet := a.cfg.Output.Quiet
			var files []media.File
			if liveOnly {
				analysis, err := a.analyzeWith(ctx, client, analyzeOptions{showProgress: !quiet})
				if err != nil {
					return err
				}
				orphans := analysis.OrphanSet()
				scanned := analysis.Scan()
				files = make([]media.File, 0, len(scanned.Files))
				for _, f := range scanned.Files {
					if _, dead := orphans[f.RelPath]; dead {
						continue
					}
					files = append(files, f)
				}
				if !quiet {
					fmt.Fprintf(a.stderr, "  %d of %d files are still referenced\n",
						len(files), len(scanned.Files))
				}
			} else {
				var scanProgress func(int64)
				if !quiet {
					printer := a.progressPrinter("  indexed")
					scanProgress = func(n int64) { printer(n, 0) }
				}
				scan, err := media.Scan(ctx, mediaRoot, media.ScanOptions{
					Workers: a.cfg.Scan.Workers,
					// The cache tree is this command's output. Indexing it
					// would pair generated files with size sets and multiply
					// the work for nothing.
					IncludeCache: false,
					ExcludeGlobs: a.cfg.Scan.ExcludeGlobs,
					Progress:     scanProgress,
				})
				if err != nil {
					return err
				}
				if !quiet {
					fmt.Fprintf(a.stderr, "\r  indexed %d files (%s)\n",
						len(scan.Files), media.HumanBytes(scan.Bytes))
				}
				files = scan.Files
			}

			plan, err := warm.BuildPlan(mediaRoot, files, sizeSets, base)
			if err != nil {
				return err
			}

			// Progress lines are written from the worker goroutines, so the
			// "did we print anything" flag has to be atomic.
			var progressLines atomic.Int64
			if !quiet {
				opts.Progress = func(done, total int64, _ string) {
					progressLines.Add(1)
					fmt.Fprintf(a.stderr, "\r  requested %d/%d", done, total)
				}
			}

			res, runErr := warm.Run(ctx, plan, opts)
			if progressLines.Load() > 0 {
				fmt.Fprintln(a.stderr)
			}

			// This block describes the plan, not the outcome: "to request" is
			// how much work there is, which is what a dry run is asked for and
			// what an applying run is measured against. What actually happened
			// is reported separately below, so the two cannot be confused.
			fmt.Fprintf(a.stdout, "%-14s: %s\n", "media root", mediaRoot)
			fmt.Fprintf(a.stdout, "%-14s: %s\n", "base url", base.String())
			fmt.Fprintf(a.stdout, "%-14s: %d (%s)\n", "size sets", len(sizeSets), source)
			// "N of M files" rather than two separate rows: only the images can
			// be paired with a size set, so this is the number that multiplies
			// out to the variants below.
			fmt.Fprintf(a.stdout, "%-14s: %d of %d files\n", "images",
				warm.WarmableFiles(files), len(files))
			fmt.Fprintf(a.stdout, "%-14s: %d\n", "variants", res.Candidates)
			fmt.Fprintf(a.stdout, "%-14s: %d\n", "already cached", res.Skipped)
			fmt.Fprintf(a.stdout, "%-14s: %d\n", "to request", res.Pending)

			if res.Pending == 0 {
				fmt.Fprintf(a.stdout, "\nnothing to do: every variant is already cached\n")
				return nil
			}
			if !apply {
				fmt.Fprintf(a.stdout, "\nrun again with --apply to issue the requests\n")
				return nil
			}

			// OK counts every 2xx, and the pre-flight request is one of them:
			// the variant it asks for really is generated, so it belongs in
			// the total rather than being quietly excluded.
			fmt.Fprintf(a.stdout, "\nwarmed %d of %d variants in %s\n",
				res.OK, res.Pending, res.Duration.Round(time.Millisecond))
			fmt.Fprintf(a.stdout, "  requests  : %d\n", res.Requests)
			if res.ClientErrors > 0 {
				fmt.Fprintf(a.stdout, "  rejected  : %d (4xx)\n", res.ClientErrors)
			}
			if res.ServerErrors > 0 {
				fmt.Fprintf(a.stdout, "  server    : %d (5xx)\n", res.ServerErrors)
			}
			if res.TransportErrors > 0 {
				fmt.Fprintf(a.stdout, "  transport : %d (never completed)\n", res.TransportErrors)
			}
			if res.Other > 0 {
				fmt.Fprintf(a.stdout, "  other     : %d\n", res.Other)
			}
			if res.Truncated {
				fmt.Fprintf(a.stdout, "  truncated : --max-requests reached\n")
			}

			if res.Truncated {
				fmt.Fprintf(a.stdout, "\nrun again to continue: variants that now exist are skipped without a request\n")
			}
			if runErr != nil {
				return runErr
			}
			if failed := res.Failures(); failed > 0 {
				fmt.Fprintf(a.stdout, "\n%d requests did not return 2xx; a visitor will trigger those variants on demand\n",
					failed)
			}
			return nil
		},
	}

	fl := cmd.Flags()
	fl.BoolVar(&apply, "apply", false, "issue the requests (default is a dry run)")
	fl.StringVar(&baseURL, "base-url", "",
		"storefront base URL (default: web/secure/base_url from core_config_data, which needs the database)")
	fl.StringSliceVar(&hashes, "cache-hash", nil,
		"size-set hash to warm, repeatable (default: discovered from the cache directory)")
	fl.StringVar(&hashFile, "hash-file", "",
		"read size-set hashes from this file (default warm.hashFile)")
	fl.IntVar(&concurrency, "concurrency", 0,
		"parallel requests (default warm.concurrency, 4)")
	fl.DurationVar(&timeout, "timeout", 0,
		"timeout for one request (default warm.timeout, 30s)")
	fl.StringVar(&method, "method", "",
		"get or head (default warm.method, get)")
	fl.StringVar(&userAgent, "user-agent", "",
		"User-Agent header to send (default: names and versions the tool)")
	fl.IntVar(&rate, "rate", 0,
		"cap on request starts per second across all workers, 0 = no limit")
	fl.IntVar(&maxRequests, "max-requests", 0,
		"stop after this many requests, 0 = no limit")
	fl.Float64Var(&maxErrorFraction, "max-error-fraction", 0,
		"abort when the share of failed requests exceeds this, 0-1 (default warm.maxErrorFraction, 0.05)")
	fl.BoolVar(&liveOnly, "live-only", false,
		"warm only images that are still referenced (needs the database, runs the full analysis)")
	fl.BoolVar(&noProbe, "no-probe", false,
		"skip the pre-flight check that a request produces a cache file")
	return cmd
}
